[shell]
program = "/usr/local/bin/fish"

[font]
normal = { family = "SauceCodeProNerdFontMono", style = "Regular" }
bold = { family = "SauceCodeProNerdFontMono", style = "Bold" }
italic = { family = "SauceCodeProNerdFontMono", style = "Italic" }
bold_italic = { family = "SauceCodeProNerdFontMono", style = "Bold Italic" }
size = 16.0

[window]
padding = { x = 40, y = 20 }
opacity = 0.07
blur = true

[colors.primary]
background = "#FFFFFF"
